[package]
name = "solana-signature-grinder-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.16"
ed25519-dalek = "1.0"
rand = "0.7"
sha2 = "0.10"
hex = "0.4"
rayon = "1.5"
bs58 = "0.4.0"